//Faça um programa que multiplique 2 números e o resultado adicione 10

const numberZero = 2
const numberOne = 30
let MyfirstMath = `A conta e de multiplicação ${numberZero}*${numberOne}=${numberZero*numberOne}`
const result = numberZero*numberOne
let MyResultmore10 = `Com a soma de mais 10 o resultado fica = ${result+10} `

console.log(numberZero)
console.log(numberOne)
console.log(MyfirstMath)
console.log(MyResultmore10)
