//[ ] Faça um programa que encontre a raiz quadrada de um número, 
//multiplique o resultado por 10 e divida por 33

let numberZero = 2
const numberOne = 10
const numberTwo = 33
let MyfirstMath = `A conta e de raiz quadrada do numero ${numberZero}* mais o numero
${numberOne} e depois vai ser dividido por 33 `
const result = Math.sqrt(numberZero,2)*numberOne/numberTwo


console.log(numberZero)
console.log(numberOne)
console.log(MyfirstMath)
console.log(result)