//9-[ ] Criei 5 Objetos, neles devem conter os dados de 5 pessoas que você conhece. 
//Mínimo 4 dados por pessoa.

const personZero = {
    name: "Arthur",
    sex: "male",
    age: 28,
    nationality: "Brasil"

}
const personOne = {
    name: "Valeria",
    sex: "famale",
    age: 28,
    nationality: "Brasil"
}
const personTwo = {
    name: "Monica",
    sex: "female",
    age: 28,
    nationality: "Brasil"
}
const personThree = {
    name: "Pierre",
    sex: "male",
    age: 28,
    nationality: "Brasil"
}
const personFour = {
    name: "Georgia",
    sex: "female",
    age: 28,
    nationality: "Brasil"
}

console.log(personZero)
console.log(personOne)
console.log(personTwo)
console.log(personThree)
console.log(personFour)